# Generated by Django 5.2.12 on 2026-03-20 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('expeired_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='inactive', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('experied_at', models.DateTimeField(blank=True, null=True)),
                ('port_range_start', models.PositiveIntegerField(default=20000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('port_range_end', models.PositiveIntegerField(default=30000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('allowed_proxy_types', models.JSONField(default=list)),
                ('max_active_proxies', models.PositiveIntegerField(default=1)),
                ('max_bandwidth_mbps', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_average_bandwidth_mbps', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_bandwidth_window_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_concurrent_conns', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proxy_name', models.CharField(max_length=255)),
                ('proxy_type', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('stcp', 'STCP'), ('sudp', 'SUDP'), ('http', 'HTTP'), ('https', 'HTTPS')], max_length=20)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_leases', to='core.accesstoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_leases', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='core.user'),
        ),
    ]
