# Generated by Django 5.2.12 on 2026-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_expeired_at_accesstoken_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylease',
            name='run_id',
            field=models.CharField(default='jk', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
