# Generated by Django 5.2.12 on 2026-03-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proxylease_run_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='experied_at',
            new_name='expired_at',
        ),
    ]
