# Generated by Django 5.2.12 on 2026-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_experied_at_user_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylease',
            name='run_id',
            field=models.CharField(max_length=64),
        ),
    ]
